[2021-07-02 14:29:34,351] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: get_data_patient_and_diseases.storing_tasks.write_diseases 2021-07-02T14:29:25.762239+00:00 [queued]>
[2021-07-02 14:29:34,385] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: get_data_patient_and_diseases.storing_tasks.write_diseases 2021-07-02T14:29:25.762239+00:00 [queued]>
[2021-07-02 14:29:34,386] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:29:34,386] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-02 14:29:34,387] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:29:34,406] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): storing_tasks.write_diseases> on 2021-07-02T14:29:25.762239+00:00
[2021-07-02 14:29:34,411] {standard_task_runner.py:52} INFO - Started process 6368 to run task
[2021-07-02 14:29:34,423] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_data_patient_and_diseases', 'storing_tasks.write_diseases', '2021-07-02T14:29:25.762239+00:00', '--job-id', '1086', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_Data_Patient.py', '--cfg-path', '/tmp/tmp1mg7f0zn', '--error-file', '/tmp/tmp71_d4qs3']
[2021-07-02 14:29:34,425] {standard_task_runner.py:77} INFO - Job 1086: Subtask storing_tasks.write_diseases
[2021-07-02 14:29:34,560] {logging_mixin.py:104} INFO - Running <TaskInstance: get_data_patient_and_diseases.storing_tasks.write_diseases 2021-07-02T14:29:25.762239+00:00 [running]> on host airflowvm
[2021-07-02 14:29:34,707] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_data_patient_and_diseases
AIRFLOW_CTX_TASK_ID=storing_tasks.write_diseases
AIRFLOW_CTX_EXECUTION_DATE=2021-07-02T14:29:25.762239+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-02T14:29:25.762239+00:00
[2021-07-02 14:29:34,726] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/airflow/dags/get_Data_Patient.py", line 64, in _write_users
    users = json.loads(users)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2021-07-02 14:29:34,728] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=get_data_patient_and_diseases, task_id=storing_tasks.write_diseases, execution_date=20210702T142925, start_date=20210702T142934, end_date=20210702T142934
[2021-07-02 14:29:34,797] {local_task_job.py:151} INFO - Task exited with return code 1
