[2021-06-30 08:09:19,306] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: open_aq.store_data 2021-06-29T00:00:00+00:00 [queued]>
[2021-06-30 08:09:19,405] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: open_aq.store_data 2021-06-29T00:00:00+00:00 [queued]>
[2021-06-30 08:09:19,406] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-30 08:09:19,406] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-30 08:09:19,407] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-30 08:09:19,521] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): store_data> on 2021-06-29T00:00:00+00:00
[2021-06-30 08:09:19,550] {standard_task_runner.py:52} INFO - Started process 2613 to run task
[2021-06-30 08:09:19,588] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'open_aq', 'store_data', '2021-06-29T00:00:00+00:00', '--job-id', '747', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/open_aq.py', '--cfg-path', '/tmp/tmpqtxbp8cw', '--error-file', '/tmp/tmp46bzqskw']
[2021-06-30 08:09:19,607] {standard_task_runner.py:77} INFO - Job 747: Subtask store_data
[2021-06-30 08:09:19,926] {logging_mixin.py:104} INFO - Running <TaskInstance: open_aq.store_data 2021-06-29T00:00:00+00:00 [running]> on host airflowvm
[2021-06-30 08:09:20,407] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=open_aq
AIRFLOW_CTX_TASK_ID=store_data
AIRFLOW_CTX_EXECUTION_DATE=2021-06-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-29T00:00:00+00:00
[2021-06-30 08:09:20,409] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-30 08:09:20,410] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo -e ".separator ";"\n.import /tmp/processed_data.csv open_aq" | sudo -u *** psql /home/airflow/airflow/airflow.db']
[2021-06-30 08:09:20,465] {subprocess.py:75} INFO - Output:
[2021-06-30 08:09:20,486] {subprocess.py:79} INFO - .separator
[2021-06-30 08:09:20,497] {subprocess.py:79} INFO - bash: line 1:
[2021-06-30 08:09:20,497] {subprocess.py:79} INFO - .import /tmp/processed_data.csv open_aq: No such file or directory
[2021-06-30 08:09:20,553] {subprocess.py:79} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2021-06-30 08:09:20,556] {subprocess.py:83} INFO - Command exited with return code 1
[2021-06-30 08:09:20,620] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-06-30 08:09:20,629] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=open_aq, task_id=store_data, execution_date=20210629T000000, start_date=20210630T080919, end_date=20210630T080920
[2021-06-30 08:09:20,778] {local_task_job.py:151} INFO - Task exited with return code 1
