[2021-06-29 13:59:59,467] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: open_aq.store_data 2021-06-29T13:59:42.397825+00:00 [queued]>
[2021-06-29 13:59:59,491] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: open_aq.store_data 2021-06-29T13:59:42.397825+00:00 [queued]>
[2021-06-29 13:59:59,492] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-29 13:59:59,494] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-29 13:59:59,495] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-29 13:59:59,520] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): store_data> on 2021-06-29T13:59:42.397825+00:00
[2021-06-29 13:59:59,528] {standard_task_runner.py:52} INFO - Started process 19109 to run task
[2021-06-29 13:59:59,534] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'open_aq', 'store_data', '2021-06-29T13:59:42.397825+00:00', '--job-id', '561', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/open_aq.py', '--cfg-path', '/tmp/tmp84nl017e', '--error-file', '/tmp/tmpbjfcux8_']
[2021-06-29 13:59:59,535] {standard_task_runner.py:77} INFO - Job 561: Subtask store_data
[2021-06-29 13:59:59,630] {logging_mixin.py:104} INFO - Running <TaskInstance: open_aq.store_data 2021-06-29T13:59:42.397825+00:00 [running]> on host airflowvm
[2021-06-29 13:59:59,751] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=open_aq
AIRFLOW_CTX_TASK_ID=store_data
AIRFLOW_CTX_EXECUTION_DATE=2021-06-29T13:59:42.397825+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-29T13:59:42.397825+00:00
[2021-06-29 13:59:59,752] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-29 13:59:59,754] {subprocess.py:63} INFO - Running command: ['bash', '-c', './psql -d *** -U *** -c \n                              "\\copy open_aq from /tmp/processed_data.csv \n                              delimiter \',\' csv header;" ']
[2021-06-29 13:59:59,765] {subprocess.py:75} INFO - Output:
[2021-06-29 13:59:59,766] {subprocess.py:79} INFO - bash: ./psql: No such file or directory
[2021-06-29 13:59:59,767] {subprocess.py:79} INFO - bash: line 2: \copy open_aq from /tmp/processed_data.csv
[2021-06-29 13:59:59,767] {subprocess.py:79} INFO -                               delimiter ',' csv header;: No such file or directory
[2021-06-29 13:59:59,767] {subprocess.py:83} INFO - Command exited with return code 127
[2021-06-29 13:59:59,786] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-06-29 13:59:59,789] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=open_aq, task_id=store_data, execution_date=20210629T135942, start_date=20210629T135959, end_date=20210629T135959
[2021-06-29 13:59:59,833] {local_task_job.py:151} INFO - Task exited with return code 1
